<template>
  <section class="base-loader">
    <div>
      <img src="../assets/loader.svg" alt="" />
    </div>
  </section>
</template>
<style lang="scss" scoped>
@import "../styles/base";
.base-loader {
  width: 100%;
  height: 100%;
  position: absolute;
  background: rgba(var(--color-primary-rgba), 0.7);
  backdrop-filter: blur(10px);
  top: 0;
  overflow: hidden;
  @media (max-width: 1270px) {
    height: calc(100% - 9rem);
    top: 9rem;
  }
  div {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    img {
      width: 10rem;
      height: 10rem;
    }
  }
}
/* generated by https://loading.io/ */
</style>
